"""Send the latest .pptx digest via Gmail API with OAuth.

First run opens a browser to authorize; a token.json is stored for reuse.
Recipient is taken from DIGEST_RECIPIENT_EMAIL in .env.
"""
import base64
import os
import sys
from email.message import EmailMessage

from util_io import TMP, ROOT, read_json, load_env, now_utc, commit_seen

load_env()

SCOPES = ["https://www.googleapis.com/auth/gmail.send"]
TOKEN_PATH = ROOT / "token.json"
CREDS_PATH = ROOT / "credentials.json"


def latest_pptx():
    files = sorted(TMP.glob("ai_digest_*.pptx"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not files:
        print("ERROR: no .pptx found in .tmp/ — run build_pptx_digest.py first", file=sys.stderr)
        sys.exit(1)
    return files[0]


def gmail_service():
    try:
        from google.auth.transport.requests import Request
        from google.oauth2.credentials import Credentials
        from google_auth_oauthlib.flow import InstalledAppFlow
        from googleapiclient.discovery import build
    except ImportError:
        print("ERROR: pip install google-api-python-client google-auth-httplib2 "
              "google-auth-oauthlib", file=sys.stderr)
        sys.exit(1)

    creds = None
    if TOKEN_PATH.exists():
        creds = Credentials.from_authorized_user_file(str(TOKEN_PATH), SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not CREDS_PATH.exists():
                print(f"ERROR: {CREDS_PATH} missing. Download OAuth client credentials "
                      "from Google Cloud Console and save as credentials.json.", file=sys.stderr)
                sys.exit(1)
            flow = InstalledAppFlow.from_client_secrets_file(str(CREDS_PATH), SCOPES)
            creds = flow.run_local_server(port=0)
        TOKEN_PATH.write_text(creds.to_json())
    return build("gmail", "v1", credentials=creds)


def _cookies_warning(digest):
    """Return an HTML warning banner if transcripts were blocked and tips are empty."""
    tips_empty = not digest.get("tools_and_tips")
    transcripts_path = TMP / "transcripts.json"
    blocked = False
    if transcripts_path.exists():
        import json as _json
        try:
            meta = _json.loads(transcripts_path.read_text())
            blocked = meta.get("blocked", False)
        except Exception:
            pass
    if tips_empty and blocked:
        return (
            '<div style="background:#fff3cd;border:1px solid #ffc107;border-radius:4px;'
            'padding:12px 16px;margin:16px 0;">'
            '<b style="color:#856404;">⚠ Action needed: YouTube cookies expired</b><br>'
            '<span style="color:#533f03;font-size:13px;">'
            'The Tools &amp; Tips slide is empty this week because YouTube blocked transcript '
            'fetching — your cookies have likely expired. '
            'Export fresh cookies from your browser and update the '
            '<b>YOUTUBE_COOKIES</b> secret in Modal to restore this section.'
            '</span></div>'
        )
    return ""


def build_html_body(digest):
    bullets = "".join(f"<li>{b}</li>" for b in digest.get("executive_summary", [])[:5])
    stories = "".join(
        f"<li><b>{s.get('provider','')}</b> — "
        f"<a href='{s.get('url','#')}'>{s.get('headline','')}</a></li>"
        for s in digest.get("top_stories", [])[:5]
    )
    warning = _cookies_warning(digest)
    return f"""<html><body style="font-family:Calibri,Arial,sans-serif;color:#0B1F3A;max-width:640px;">
<h2 style="color:#0B1F3A;border-bottom:3px solid #FF6B35;padding-bottom:6px;">AI Industry Weekly</h2>
{warning}<p style="color:#5a5a5a;">The full briefing is attached as a slide deck. Quick preview below.</p>
<h3>Executive summary</h3>
<ul>{bullets or '<li>Quiet week.</li>'}</ul>
<h3>Top stories</h3>
<ul>{stories or '<li>None this week.</li>'}</ul>
<hr><p style="color:#888;font-size:11px;">Generated by the WAT weekly digest automation.</p>
</body></html>"""


def main():
    recipient = os.environ.get("DIGEST_RECIPIENT_EMAIL")
    if not recipient:
        print("ERROR: DIGEST_RECIPIENT_EMAIL not set in .env", file=sys.stderr)
        sys.exit(1)

    pptx = latest_pptx()
    digest = read_json(TMP / "digest.json") if (TMP / "digest.json").exists() else {}

    msg = EmailMessage()
    date_label = now_utc().strftime("%b %d, %Y")
    msg["Subject"] = f"AI Industry Weekly — {date_label}"
    msg["To"] = recipient
    msg.set_content("Your weekly AI industry digest is attached.\n\n"
                    "(HTML preview in email clients; .pptx attached for full briefing.)")
    msg.add_alternative(build_html_body(digest), subtype="html")

    with open(pptx, "rb") as f:
        msg.add_attachment(
            f.read(),
            maintype="application",
            subtype="vnd.openxmlformats-officedocument.presentationml.presentation",
            filename=pptx.name,
        )

    service = gmail_service()
    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
    sent = service.users().messages().send(userId="me", body={"raw": raw}).execute()
    print(f"Done. Sent to {recipient} (Gmail id={sent.get('id')}), attached {pptx.name}")

    delivered_urls = [s.get("url") for s in digest.get("top_stories", []) if s.get("url")]
    delivered_vids = [v.get("videoId") for v in digest.get("trending_videos", []) if v.get("videoId")]
    if delivered_urls or delivered_vids:
        commit_seen(urls=delivered_urls, video_ids=delivered_vids)
        print(f"  marked {len(delivered_urls)} url(s) and {len(delivered_vids)} videoId(s) as seen")


if __name__ == "__main__":
    main()
